validate relay token before moving on

diff --git a/deployments/sdm-relay/templates/pre-install.yaml b/deployments/sdm-relay/templates/pre-install.yaml
--- a/deployments/sdm-relay/templates/pre-install.yaml
+++ b/deployments/sdm-relay/templates/pre-install.yaml
@@ -121,10 +121,15 @@ spec:
               /sdm.linux login --admin-token="${SDM_ADMIN_TOKEN}"
             {{- $commonArgs := printf "--maintenance-windows %s --name %s --tags %s" (squote .Values.strongdm.autoCreateNode.maintenanceWindows) (squote .Values.strongdm.autoCreateNode.name) (squote .Values.strongdm.autoCreateNode.tags) }}
             {{- if .Values.strongdm.gateway.enabled }}
-              echo "SDM_RELAY_TOKEN=$(/sdm.linux admin node create-gateway {{ $commonArgs }} {{ .Values.strongdm.gateway.listenAddress }}:{{ .Values.strongdm.gateway.listenPort }})" > /secrets/token
+              SDM_RELAY_TOKEN=$(/sdm.linux admin node create-gateway {{ $commonArgs }} {{ .Values.strongdm.gateway.listenAddress }}:{{ .Values.strongdm.gateway.listenPort }})"
             {{- else }}
-              echo "SDM_RELAY_TOKEN=$(/sdm.linux admin node create {{ $commonArgs }})" > /secrets/token
+              SDM_RELAY_TOKEN=$(/sdm.linux admin node create {{ $commonArgs }})"
             {{- end }}
+              if [[ ! grep -qE "^[[:graph:]]+[.][[:graph:]]+[.][[:graph:]]+$" <<< "${SDM_RELAY_TOKEN}" ]]; then
+                echo "Error creating node: ${SDM_RELAY_TOKEN}"
+                exit 3;
+              fi
+              echo "${SDM_RELAY_TOKEN}" /secrets/token
       containers:
         - name: kubectl
           {{- $kubeVersion := semver .Capabilities.KubeVersion.Version }}
